version: '3.8'
services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
